### ISSUE TITLE
please follow a PR based flow

### ISSUE THREAD

**Issue by cordoval** [Tuxion/DoctrineRest#1]
this means do not commit to master as we will get notified if you do use PRs to follow up best

**Comment by Beanow** [comment]
Yes currently the development is in the `develop` branch only. The first release will be using a release branch + pull request. As per git-flow concepts.

**Comment by cordoval** [comment]
not sure you get what i said about avoiding commits to master. But ok. :blush: I am closing now. Just wanted to ask about this.

**Comment by cordoval** [comment]
looks good btw :blush: :+1:

**Comment by Beanow** [comment]
Commits directly to the master may be documentation changes only. Code changes happen in a different branch and will go through pull requests. Following http://nvie.com/posts/a-successful-git-branching-model/

I didn't follow this at first, but since the first beta version is due soon I'm sticking to this now.

Thanks for the tip though, I did not consider using pull requests for the sake of notifications before :]
